name = "clubserve"
type = "javascript"
main = "functions/submit-form.ts"
account_id = "" # Add your Cloudflare account ID
workers_dev = true

[env.production]
routes = [
  { pattern = "clubserve.com/api/submit-form", zone_name = "clubserve.com" }
]

[build]
command = "npm run build"
cwd = "./"
watch_paths = ["src/**/*.ts"]

[env.production.build]
command = "npm run build"

[vars]
FORMSTACK_API_URL = "https://www.formstack.com/api/v2"
FORMSTACK_FORM_ID = ""

# Environment-specific variables
[env.production.vars]
FORMSTACK_API_URL = "https://www.formstack.com/api/v2"
